
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import AuthContextProvider from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
<Navbar/>

          {children}
          <ToastContainer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
